Sitecore10.1
Sitecore/Helix.Examples pull request #117
Opened 2021-04-18 08:00 UTC by navancommits

sitecore 10.1 tds examples tested and work fine....

2021-04-18 08:01 UTC, navancommits commented
Please reject the other PR that is based on master branch.....

2021-04-29 17:58 UTC, nickwesselman requested changes
Thanks so much! This is a good start, can you do the following as well? If not, I can also do in a follow-up PR.

- [ ] Add the new `SITECORE_DEVELOPMENT_PATCHES` to CM and CD. [Example](https://github.com/Sitecore/Helix.Examples/commit/6f2290c77a8302a1b243bd3f59eb94d36b38920a#diff-e00389ce3737ab7acc9be22610bf7656a3024ca2b9865476fd7857a123214251R140-R141)
- [ ] Update `PlatformVersion` in `Packages.props` in order to update NuGet references
- [ ] Change all uses of `Set-DockerComposeEnvFileVariable` in `init.ps1` scripts to the new `Set-EnvFileVariable`

2021-04-29 17:58 UTC, nickwesselman commented on examples/helix-basic-tds/.env
> +SOLR_CORE_PREFIX_NAME=basictds
Can we keep this consistent across the examples and just remain `sitecore`? No reason for them to be unique in containers.

2021-04-30 15:22 UTC, nickwesselman approved these changes
LGTM thanks so much for the contribution!

2021-04-30 15:22 UTC, merged